name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name:  Install Valgrind
      run:  sudo apt-get install valgrind -y
    - uses: actions/checkout@v1
    - name: change mode
      run:  chmod a+x client.o && chmod a+x server.o
    - name: Valgrind
      run: valgrind ./client.o && valgrind ./server.o 
